# Generated by Django 4.0.6 on 2023-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeswapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
